default_platform(:ios)

platform :ios do

  desc "Run unit tests (CI)"
  lane :ci do
    run_tests(
      scheme: "TestCICD",
      devices: ["iPhone 16 Pro (18.4)"],
      only_testing: ["TestCICDTests"],
      clean: true
    )
  end

end
