default_platform(:ios)

platform :ios do

  desc "Run unit tests (CI)"
  lane :ci do
    run_tests(
      scheme: "TestCICD",
      device: "iPhone 17",
      only_testing: ["TestCICDTests"],
      clean: true
    )
  end

end
